version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

volumes:
  pgdata: {}
